name: CPPLINT
on: [push]
jobs:
  run-cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint && cpplint --version

      - name: Run cpplint
        run: cpplint --recursive srcs
        
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
